# Turn light on / off if xiaomi button is clicked long
- alias: xiaomi_liv_hold
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00011033aa
      click_type: hold
  action:
    - service_template: >
        {%- if states.group.light_living_room.state == "off" -%}
          scene.turn_on
        {%- else -%}
          light.turn_off
        {%- endif -%}
      data_template:
        entity_id: >
          {%- if states.group.light_living_room.state == "off" -%}
            scene.living_room_normal
          {%- else -%}
            group.light_living_room
          {%- endif -%}