- platform: template
  sensors:
    guestroomm2p:
      entity_id: device_tracker.bedroom
      value_template: >
        {% if is_state('device_tracker.bedroom', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'RaspberryPi (Bedroom)'