- platform: template
  sensors:
    broadlinkrmpro:
      entity_id: device_tracker.broadlinkrmpro
      value_template: >
        {% if is_state('device_tracker.broadlinkrmpro', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Broadlink RM Pro (IR/RF)'