- platform: template
  sensors:
    guestroomm2p:
      entity_id: device_tracker.guestroom
      value_template: >
        {% if is_state('device_tracker.guestroom', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'RaspberryPi 2 (Guest room)'