- platform: template
  sensors:
    janis_fire7:
      entity_id: device_tracker.janis_fire7
      value_template: >
        {% if is_state('device_tracker.janis_fire7', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Janis Tablet'