- platform: template
  sensors:
    kitchenmpd:
      entity_id: device_tracker.kitchen
      value_template: >
        {% if is_state('device_tracker.kitchen', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'RaspberryPi 2 (Kitchen)'