- platform: template
  sensors:
    kitchenm2p:
      entity_id: device_tracker.kitchen
      value_template: >
        {% if is_state('device_tracker.kitchen', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'RaspberryPi (Kitchen)'