- platform: template
  sensors:
    lena_laptop:
      entity_id: device_tracker.lena_laptop
      value_template: >
        {% if is_state('device_tracker.lena_laptop', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Lena Laptop'