- platform: template
  sensors:
    milightbridge:
      entity_id: device_tracker.milightbridge
      value_template: >
        {% if is_state('device_tracker.milightbridge', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'MiLight-Bridge'