- platform: template
  sensors:
    nexus7living_room:
      entity_id: device_tracker.nexus7living_room
      value_template: >
        {% if is_state('device_tracker.nexus7living_room', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Nexus 7 living room'