name: Services Backend
control: hidden
entities:
  - switch.mosquitto
  - switch.influxdb
  - switch.transmission_service
  - switch.mysql
  - switch.asf
  - switch.telegram_bot
  - switch.7d2d
  - switch.discordbot