name: Services Backend
control: hidden
entities:
  - switch.mosquitto
  - switch.influxdb
  - switch.transmission_service
  - switch.mysql
  - switch.asf
  - switch.telegram_bot
  - switch.sdtd
  - switch.project_zomboid
  - switch.discordbot