- platform: darksky
  api_key: !secret darksky_api
  forecast:
   - 1
   - 2
  monitored_conditions:
    - temperature
    - apparent_temperature
    - cloud_cover
    - humidity
    - temperature_max
    - precip_probability
    - precip_type
    - summary