- platform: transmission
  host: localhost
  port: 9091
  username: !secret transmission_user
  password: !secret transmission_pwd
  name: Transmission
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'