# Turn light on, on motion
- alias: motion_light_hallway
  trigger:
    - platform: event
      event_type: motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d0001307b02
  action:
    - service: light.turn_on
      data:
        entity_id: group.light_hallway
