sequence:
  - service: script.turn_off
    data:
      entity_id: script.party_lights_loop
  - service: script.turn_off
    data:
      entity_id: script.party_lights_pause
  - service: scene.turn_on
    data:
      entity_id: scene.livingroom_normal