# Turn on and play/pause music if kitchen butten is pressed
- alias: xiaomi_kit_click
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00013f9ad7
      click_type: single
  action:
    - service_template: >
        {% if states.media_player.kitchen.state == 'off' %}
          media_player.turn_on
        {% elif states.media_player.kitchen.state != 'playing' and states.media_player.kitchen.state != 'off' %}
          media_player.media_play
        {% else %}
          media_player.media_pause
        {% endif %}
      data:
        entity_id: media_player.kitchen