sensor:
  - platform: template
    sensors:
      alarmtime_janis:
        friendly_name: Wakeup Time
        entity_id:
         - input_number.alarm_hour_janis
         - input_number.alarm_minutes_janis
        value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarm_hour_janis") | int, states("input_number.alarm_minutes_janis") | int) }}'
      nextalarm_janis:
        friendly_name: Seconds until next alarm
        entity_id:
         - input_number.alarm_hour_janis
         - input_number.alarm_minutes_janis
        value_template: >
          {% set relative_time =  (states.input_number.alarm_hour_janis.state|float|multiply(60) + states.input_number.alarm_minutes_janis.state|float) - (now().hour|float|multiply(60) + now().minute) %}
          {%- if relative_time < 0 -%}
                   {{23*60+relative_time}}
          {%- else -%}
                   {{ relative_time-60}}
          {%- endif %}
      time_until_alarm_janis:
        friendly_name: Time until next alarm
        entity_id:
         - sensor.nextalarm_janis
        value_template: '{{  (states.sensor.nextalarm_janis.state.split(" ")[0] | int *60 ) | timestamp_custom("%H:%M") }}'

automation:
  - alias: SetJanisAlarmHour
    trigger:
      platform: mqtt
      topic: "setHourJanis"
    action:
      - service: input_number.select_value
        data_template:
          entity_id: input_number.alarm_hour_janis
          value: '{{ trigger.payload}}'
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.alarm_clock_janis

  - alias: SetJanisAlarmMinutes
    trigger:
      platform: mqtt
      topic: "setMinutesJanis"
    action:
      - service: input_number.select_value
        data_template:
          entity_id: input_number.alarm_minutes_janis
          value: '{{ trigger.payload}}'
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.alarm_clock_janis

  - alias: alarmClockJanis
    trigger:
      platform: time
      minutes: '/1'
      seconds: '0'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ ((now().strftime("%s") | int + 1200) | timestamp_custom("%H:%M")) == states.sensor.alarmtime_janis.state  }}'
        - condition: state
          entity_id: input_boolean.alarm_clock
          state: 'on'
    action:
      - service: scene.turn_on
        data:
          entity_id: scene.normal_light
      - service: media_player.turn_on
        data:
          entity_id: media_player.txnr414
      - service: media_player.play_media
        data_template:
          entity_id: media_player.kodi_on_firetv
          media_content_id: >
              {% if is_state("input_select.radio_wakeup_janis", "Sky Radio") %} http://8623.live.streamtheworld.com:80/SKYRADIOAAC_SC
              {% elif is_state("input_select.radio_wakeup_janis", "Classic FM") %} http://19143.live.streamtheworld.com/CLASSICFM_SC
              {% endif %}
          media_content_type: 'audio/mp4'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.01'
      - delay: '00:02:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.05'
      - delay: '00:02:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.10'
      - delay: '00:01:30'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.15'
      - delay: '00:01:30'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.20'
      - delay: '00:01:30'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.25'
      - delay: '00:01:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.30'
      - delay: '00:01:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.35'
      - delay: '00:01:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.40'
      - delay: '00:01:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.45'
      - delay: '00:01:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.50'
      - delay: '00:01:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.55'
      - delay: '00:00:45'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.60'
      - delay: '00:00:45'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.65'
      - delay: '00:00:45'
      - service: media_player.volume_set
        data:
          entity_id: media_player.kodi_on_firetv
          volume_level: '0.70'
      - delay: '00:02:00'
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.alarm_clock_janis

script:
  sleep_janis:
    alias: Good Night
    sequence:
      - alias: Set Volume
        service: media_player.volume_set
        data:
          entity_id: media_player.bedroom
          volume_level: '1.0'
      - alias: Say Sleep Left
        service: tts.google_say
        entity_id: media_player.bedroom
        data_template:
          message: 'Next alarm in {{ (states.sensor.nextalarm_janis.state.split(" ")[0] | int *60 ) | timestamp_custom("%H") | int }} hours and {{ (states.sensor.nextalarm_janis.state.split(" ")[0] | int *60 ) | timestamp_custom("%M") }} minutes . Good night.'
          cache: false
      - delay: '00:00:15'
      - alias: Set Volume2
        service: media_player.volume_set
        data:
          entity_id: media_player.bedroom
          volume_level: '0.75'

input_boolean:
  alarm_clock_janis:
    name: On/Off
    initial: off
    icon: mdi:alarm
input_number:
  alarm_hour_janis:
    name: Hour
    icon: mdi:timer
    initial: 6
    min: 0
    max: 23
    step: 1
    mode: box
  alarm_minutes_janis:
    name: Minutes
    icon: mdi:timer
    initial: 30
    min: 0
    max: 59
    step: 1
    mode: box
input_select:
  radio_wakeup_janis:
    name: Wakeup Radio Station
    options:
      - Sky Radio
      - Classic FM
    initial: Classic FM
    icon: mdi:radio

group:
 alarm_clock_janis:
  control: hidden
  name: Alarm for Janis
  entities:
  - input_boolean.alarm_clock_janis
  - sensor.alarmtime_janis
  - sensor.time_until_alarm_janis
  - input_number.alarm_hour_janis
  - input_number.alarm_minutes_janis
  - input_select.radio_wakeup_janis
