sequence:
  - condition: state
    entity_id: input_boolean.hidden_liv_dim
    state: 'off'
  - service: light.turn_on
    entity_id: group.light_living_room
    data_template:
      brightness: '{{states.light.living_left.attributes.brightness + 10}}'
  - service: script.turn_off
    entity_id: script.brighten_light_liv
  - service: script.turn_on
    entity_id: script.brighten_light_liv
