sequence:
      - condition: state
        entity_id: input_boolean.hidden_liv_dim
        state: 'on'
      - service: light.turn_on
        entity_id: group.light_living_room
        data_template:
          brightness: '{{states.light.living_left.attributes.brightness - 10}}'
      - service: script.turn_off
        entity_id: script.dim_light_liv
      - service: script.turn_on
        entity_id: script.dim_light_liv
