- platform: command_line
  switches:
    influxdb:
      command_on: 'sudo /etc/init.d/influxdb start'
      command_off: 'sudo /etc/init.d/influxdb stop'
      command_state: 'ps aux | grep -q "influxd -config /etc/influxdb/influxdb.conf$"'