# Dim lights if dinner mode is disabled while media is playing
- alias: dim_kodi_while_playing
  trigger:
    - platform: state
      entity_id: input_boolean.dinner_mode
      to: 'off'
  condition:
    condition: state
    entity_id: media_player.kodi_on_firetv
    state: 'playing'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.livingroom_dim