# Turn gateway light on if janis sits at his desk
- alias: gateway_desk
  trigger:
    - platform: state
      entity_id: sensor.find_janis
      to: 'desk'
      for:
        minutes: 5
  condition:
    condition: template
    value_template: '{{ states.device_tracker.janis_handy.state == "home" and states.sun.sun.state == "below_horizon" }}'
  action:
    - service: light.turn_on
      data:
        entity_id: light.gateway_light_286c07889d7e
        rgb_color: [0, 255, 0]
        brightness: 255