- name: Bedtime
  entities:
    group.light_living_room: off
    input_boolean.blue_light: off
    input_boolean.led_strip: off
    input_boolean.shelf_light: off
    input_boolean.tv: off
    media_player.txnr414: off
    light.gateway_light_286c07889d7e: off