- platform: template
  sensors:
    entrance_door_open:
      entity_id: binary_sensor.door_window_sensor_158d00011c8066
      value_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d00011c8066', 'on') %}
          on
        {% else %}
          off
        {% endif %}