- platform: template
  sensors:
    balcony_door_closed:
      entity_id: binary_sensor.door_window_sensor_158d00011c8066
      value_template: >
        {% if is_state('binary_sensor.door_window_sensor_158d00011c8066', 'off') %}
          on
        {% else %}
          off
        {% endif %}