name: Other Services (LAN only)
entities:
  - weblink.flexget
  - weblink.emby
  - weblink.ombi
  - weblink.grafana
  - weblink.mayan_edms
  - weblink.owncloud
  - weblink.find
  - weblink.sonarr
  - weblink.radarr
  - weblink.headphones
  - weblink.jackett