# Turn off hidden switch if motion is disabled
- alias: disable_motion
  trigger:
    platform: state
    entity_id: input_boolean.disable_motion_light_livingroom
    to: 'off'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.livingroom_motion_timer