# Start flexget buffer for AnimeBytes if input is set
- alias: flexget1
  trigger:
    - platform: time
      minutes: /10
      seconds: 00
  condition:
    condition: state
    entity_id: input_boolean.aniByBuffer
    state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.flexget_aniByBuffer

# Start flexget buffer for AHD if input is set
- alias: flexget2
  trigger:
    - platform: time
      minutes: /10
      seconds: 00
  condition:
    condition: state
    entity_id: input_boolean.ahdBuffer
    state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.flexget_ahdBuffer

# Start flexget buffer for GGn if input is set
- alias: flexget3
  trigger:
    - platform: time
      minutes: /10
      seconds: 00
  condition:
    condition: state
    entity_id: input_boolean.ggnBuffer
    state: 'on'
  action:
    - service: script.turn_on
      data:
        entity_id: script.flexget_ggnBuffer
