# Turn tv on / off with input boolean
- alias: tv
  trigger:
    - platform: state
      entity_id: input_boolean.tv
      to: 'off'
      from: 'on'
    - platform: state
      entity_id: input_boolean.tv
      to: 'on'
      from: 'off'
  action:
    - service: broadlink.send_packet_192_168_137_43
      data:
        packet:
          - !secret ir_tv_power