party_mode:
  name: Party Hard?
  icon: mdi:ambulance

dinner_mode:
  name: Dinner
  icon: mdi:food-fork-drink

media_devices:
  name: TV & Receiver
  icon: mdi:television

# HIDDEN ELEMENTS #
livingroom_motion_timer:
 name: Livingroom Motion Timer