- platform: openweathermap
  forecast:
  api_key: !secret openweathermap_api
  monitored_conditions:
    - temperature
    - weather
    - humidity
    - clouds
    - rain
    - snow

- platform: command_line
  command: hass --version
  name: HA Version
  scan_interval: 7200

- platform: command_line
  command: python -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
  name: Newest HA Version
  scan_interval: 7200

- platform: rest
  resource: http://localhost:8006/location?group=WALLISERS
  value_template: '{{ value_json.users.janis[0].location }}'
  method: GET
  name: FIND Janis
  scan_interval: 1

- platform: rest
  resource: http://localhost:8006/location?group=WALLISERS
  value_template: '{{ value_json.users.lena[0].location }}'
  method: GET
  name: FIND Lena
  scan_interval: 1

- platform: transmission
  host: localhost
  port: 9091
  username: !secret transmission_user
  password: !secret transmission_pwd
  name: Transmission
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'

- platform: time_date
  display_options:
    - "date_time"

- platform: template
  sensors:
    emby_player_uuid:
      value_template: !secret emby_player_uuid
    firetv:
      value_template: >-
        {% if is_state('device_tracker.firetv', 'home') %} 
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'FireTV'
    lena_laptop:
      value_template: >-
        {% if is_state('device_tracker.lena_laptop', 'home') %} 
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Lena Laptop'
    janis_pc:
      value_template: >-
        {% if is_state('device_tracker.janis_pc', 'home') %} 
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Burrito-Ninja (Janis PC)'
    taconinja:
      value_template: >-
        {% if is_state('device_tracker.taconinja', 'home') %} 
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Taco-Ninja (Janis Laptop)'
    milightbridge:
      value_template: >-
        {% if is_state('device_tracker.milightbridge', 'home') %} 
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'MiLight-Bridge'
    nintendo3ds:
      value_template: >-
        {% if is_state('device_tracker.nintendo3ds', 'home') %} 
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Lenas 3DS'

    janis_fire7:
      value_template: >-
        {% if is_state('device_tracker.janis_fire7', 'home') %} 
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Janis Tablet'

    nexus7livingroom:
      value_template: >-
        {% if is_state('device_tracker.nexus7livingroom', 'home') %} 
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Nexus 7 Livingroom'

    edimax1:
      value_template: >-
        {% if is_state('device_tracker.edimax1', 'home') %} 
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Edimax Switch 1 (Shelf lights)'

    xiaomi_gateway:
      value_template: >-
        {% if is_state('device_tracker.xiaomi_gateway', 'home') %} 
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'XIAOMI Gateway'

    broadlinkrmpro:
      value_template: >-
        {% if is_state('device_tracker.broadlinkrmpro', 'home') %} 
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Broadlink RM Pro (IR/RF)'

    ram:
      friendly_name: "Ram Usage"
      value_template: >-
        {{ states("sensor.ram_use") }} MB / {{ ((states("sensor.ram_use")|float) + (states("sensor.ram_free") | float)) | round(2) }} MB

    swap:
      friendly_name: Swap Usage
      value_template: >-
        {{ (states("sensor.swap_use") | float * 1000) | int }} MB / {{ (((states("sensor.swap_use") | float) + (states("sensor.swap_free") | float)) * 1000) | int }} MB

    network:
      friendly_name: In / Out
      value_template: >-
        {{ (states("sensor.received_eth0") | float / 1000) | round(2) }} GB / {{ (states("sensor.sent_eth0") | float / 1000) | round(2) }} GB

    nas_disk:
      friendly_name: NAS Usage
      value_template: >-
        {{ (states("sensor.disk_use_mntshare") | float / 1000)  | round(2) }} TB / {{ (((states("sensor.disk_use_mntshare") | float) + (states("sensor.disk_free_mntshare") |float)) / 1000) | round(2) }} TB

    uptime:
      friendly_name: Uptime
      value_template: >-
        {{ states.sensor.since_last_boot.state[0:-7] }}

    recent_episodes:
      friendly_name: Recently added episodes on Emby
      value_template: >-
        {{ states.sensor.recent_episodes.state }}

- platform: cpuspeed

- platform: systemmonitor
  resources:
    - type: disk_use
      arg: /mnt/share
    - type: disk_free
      arg: /mnt/share
    - type: swap_use
    - type: swap_free
    - type: memory_use
    - type: memory_free
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: since_last_boot
    - type: processor_use
