sensor.lena_laptop:
  icon: mdi:laptop
sensor.taconinja:
  icon: mdi:laptop
sensor.janis_pc:
  icon: mdi:desktop-tower
sensor.firetv:
  icon: mdi:amazon
sensor.milightbridge:
  icon: mdi:lightbulb-outline
sensor.edimax1:
  icon: mdi:lightbulb-outline
sensor.xiaomi_gateway:
  icon: mdi:lightbulb-outline
sensor.broadlinkrmpro:
  icon: mdi:radio-tower
sensor.nintendo3ds:
  icon: mdi:gamepad-variant
sensor.janis_fire7:
  icon: mdi:amazon
sensor.nexus7livingroom:
  icon: mdi:gamepad-variant