# Weather #
sensor.owm_temperature:
  friendly_name: 'Temperature'
# Transmission #
sensor.transmission_down_speed:
  icon: mdi:download
  friendly_name: Download Speed
sensor.transmission_up_speed:
  icon: mdi:upload
  friendly_name: Upload Speed
sensor.transmission_status:
  icon: mdi:information-outline
  friendly_name: Status
sensor.ram:
  icon: mdi:memory
sensor.swap:
  icon: mdi:harddisk
sensor.nas_disk:
  icon: mdi:harddisk
sensor.backup_disk:
  icon: mdi:harddisk
sensor.uptime:
  icon: mdi:clock
sensor.network:
  icon: mdi:mdi:ethernet
sensor.balcony_door:
  friendly_name: Balcony Door
  icon: mdi:lock-open