sequence:
  - condition: state
    entity_id: input_boolean.dinner_mode
    state: 'off'
  - condition: state
    entity_id: group.light_livingroom
    state: 'on'
  - condition: template
    value_template: '{{ Player.uuid == states("sensor.emby_player_uuid") and states.media_player.kodi_on_firetv.attributes.media_content_type != "music" }}'
  - service: script.turn_off
    data:
      entity_id: script.emby_pause_webhook_receiver
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.livingroom_motion_timer
  - service: scene.turn_on
    data:
      entity_id: scene.livingroom_dim