- name: tablet_nma
  platform: nma
  api_key: !secret nma_api
- name: janis_handy_telegram
  platform: telegram
  api_key: !secret telegram_api
  chat_id: !secret janis_chat_id
- name: lena_handy_telegram
  platform: telegram
  api_key: !secret telegram_api
  chat_id: !secret lena_chat_id