- name: Living room media
  entities:
    group.light_living_room:
      state: on
      brightness: 255
      rgb_color: [255, 255, 255]
    input_boolean.shelf_light: on
    input_boolean.led_strip: on
    input_boolean.tv: on