# Stop party mode
- alias: party_off
  trigger:
    platform: state
    entity_id: input_boolean.party_mode
    to: 'off'
  action:
    - service: script.party_over
    - service: media_player.media_stop
      data:
        entity_id: media_player.kodi_on_firetv