name: Home
latitude: !secret home_lat
longitude: !secret home_long
elevation: 96
unit_system: metric
time_zone: Europe/Berlin
customize: !include_dir_named ../customizations
packages:  !include_dir_named ../packages