- platform: template
  sensors:
    firetv:
      entity_id: device_tracker.firetv
      value_template: >
        {% if is_state('device_tracker.firetv', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'FireTV'

    lena_laptop:
      entity_id: device_tracker.lena_laptop
      value_template: >
        {% if is_state('device_tracker.lena_laptop', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Lena Laptop'

    janis_pc:
      entity_id: device_tracker.janis_pc
      value_template: >
        {% if is_state('device_tracker.janis_pc', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Burrito-Ninja (Janis PC)'

    taconinja:
      entity_id: device_tracker.taconinja
      value_template: >
        {% if is_state('device_tracker.taconinja', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Taco-Ninja (Janis Laptop)'

    milightbridge:
      entity_id: device_tracker.milightbridge
      value_template: >
        {% if is_state('device_tracker.milightbridge', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'MiLight-Bridge'

    nintendo3ds:
      entity_id: device_tracker.nintendo3ds
      value_template: >
        {% if is_state('device_tracker.nintendo3ds', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Lenas 3DS'

    janis_fire7:
      entity_id: device_tracker.janis_fire7
      value_template: >
        {% if is_state('device_tracker.janis_fire7', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Janis Tablet'

    nexus7livingroom:
      entity_id: device_tracker.nexus7livingroom
      value_template: >
        {% if is_state('device_tracker.nexus7livingroom', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Nexus 7 Livingroom'

    edimax1:
      entity_id: device_tracker.edimax1
      value_template: >
        {% if is_state('device_tracker.edimax1', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Edimax Switch 1 (Shelf lights)'

    xiaomi_gateway:
      entity_id: device_tracker.xiaomi_gateway
      value_template: >
        {% if is_state('device_tracker.xiaomi_gateway', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'XIAOMI Gateway'

    broadlinkrmpro:
      entity_id: device_tracker.broadlinkrmpro
      value_template: >
        {% if is_state('device_tracker.broadlinkrmpro', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'Broadlink RM Pro (IR/RF)'

    kitchenm2p:
      entity_id: device_tracker.kitchen
      value_template: >
        {% if is_state('device_tracker.kitchen', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'RaspberryPi (Kitchen)'

    guestroomm2p:
      entity_id: device_tracker.guestroom
      value_template: >
        {% if is_state('device_tracker.guestroom', 'home') %}
          online
        {% else %}
          offline
        {% endif %}
      friendly_name: 'RaspberryPi 2 (Guest room)'