# Turn light on if xiaomi button is clicked long
- alias: xiaomi_liv_hold
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d00011033aa
      click_type: hold
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.livingroom_normal