- name: home janis
  latitude: !secret home_lat
  longitude: !secret home_long
  radius: 100
  icon: mdi:home

- name: home lena
  latitude: !secret home_lat
  longitude: !secret home_long
  radius: 100
  icon: mdi:home