- platform: template
  sensors:
    backup_disk:
      entity_id: sensor.disk_use_mntbackup
      friendly_name: "Backup Usage"
      value_template: >
        {{ (states("sensor.disk_use_mntbackup") | float / 1000)  | round(2) }} TB / {{ (((states("sensor.disk_use_mntbackup") | float) + (states("sensor.disk_free_mntbackup") |float)) / 1000) | round(2) }} TB