# Dim lights if dinner mode is disabled while media is playing
- alias: dim_kodi_while_playing
  trigger:
    - platform: state
      entity_id: input_boolean.dinner_mode
      to: 'off'
  condition:
    condition: template
    value_template: '{{ states.media_player.kodi_on_firetv.state == "playing" and states.media_player.kodi_on_firetv.attributes.media_content_type != "music" }}'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.living_room_dim