# Turn light on, on motion
- alias: motion_light
  initial_state: 'off'
  trigger:
    - platform: event
      event_type: motion
      event_data:
        entity_id: binary_sensor.motion_sensor_158d00010f8100
  condition:
    condition: template
    value_template: '{{ states.group.light_living_room.state == "off" and states.alarm_control_panel.alarm.state == "disarmed"}}'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.living_room_normal
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.living_room_motion_timer