speech:
  text: >
    {%- if User.lower() == "janis" -%}
      Janis is at {{ states("device_tracker.janis_handy") }}. https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.janis_handy.attributes.latitude }},{{ states.device_tracker.janis_handy.attributes.longitude }}&zoom=13&size=600x600&maptype=roadmap&markers=color:blue%7Clabel:J%7C{{ states.device_tracker.janis_handy.attributes.latitude }},{{ states.device_tracker.janis_handy.attributes.longitude }}
    {%- elif User.lower() == "lena" -%}
      Lena is at {{ states("device_tracker.lena_handy") }}. https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.lena_handy.attributes.latitude }},{{ states.device_tracker.lena_handy.attributes.longitude }}&zoom=13&size=600x600&maptype=roadmap&markers=color:blue%7Clabel:L%7C{{ states.device_tracker.lena_handy.attributes.latitude }},{{ states.device_tracker.lena_handy.attributes.longitude }}
    {%- else -%}
      Sorry I do not know anybody with the name {{ User }}
    {%- endif -%}