# Start flexget buffer for AnimeBytes if input is set
- alias: aniby_buffer
  trigger:
    - platform: time
      minutes: /10
      seconds: 00
  action:
    - service: script.turn_on
      data:
        entity_id: script.flexget_aniByBuffer